---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: devops-toolkit
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: devops-toolkit
  install: {}
  interval: 30s
  targetNamespace: staging
  values:
    image:
      tag: 2.9.17
    ingress:
      host: staging.devops-toolkit.192.168.49.2.sslip.io

