---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubeapps
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kubeapps
      sourceRef:
        kind: HelmRepository
        name: bitnami
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: kubeapps
  values:
    frontend:
      replicaCount: 1
    dashboard:
      replicaCount: 1
    apprepository:
      replicaCount: 1
    kubeops:
      replicaCount: 1
